### ISSUE TITLE
Other or user configurable keyboard assist when creating XLinks

### ISSUE THREAD

**Issue by slmeyer** [insilmaril/vym#100]
Some window managers use Shift + drag mouse to move windows on screen. This prevents the creation of XLinks in Vym unfortunately. It would be nice to either be able to chose another or have some that is not so often used by window managers

**Comment by insilmaril** [comment]
Hm, I really would like to avoid adding more complexity to moving stuff (which also is creating XLinks)

Out of curiousity: which WM?  In KDE this can be configured, Windows and Mac are no problem...

**Comment by slmeyer** [comment]
Openbox, I am sure this can be configured in OpenBox too, but it was not immediately clear to me which item to edit, presumably in rc.xml. I thought this was the modifier used in OSX too, but I must have remembered incorrectly then. I agree that if it is only an issue in OB then it is not worth doing in VYM.

**Comment by insilmaril** [comment]
thanks for feedback, I'd prefer to configure in WM then
