### ISSUE TITLE
Tree editor has black text on black background

### ISSUE THREAD

**Issue by slmeyer** [insilmaril/vym#102]
After creating a new map without a default map, the tree editor is unreadable, because both text and background is black. I could not find any instructions about how to change this. other maps work well

**Comment by insilmaril** [comment]
Two questions:

a) why is there no default map?
b) Can a MapCenter be selected in MapEditor and be colored? If so, does it change color also in TreeEditor?

**Comment by insilmaril** [comment]
Is this still an issue? Which vym version actually is this and on which platform?

**Comment by slmeyer** [comment]
a) It apparently was installed without a default map 
b) Yes and Yes
c) no, not an issue anymore - maybe because I saved a default map at one point (I also have different computers, may have been one of the others.)
VYM Version 2.9.26 QT 5.15.13. Manjaro Linux

**Comment by insilmaril** [comment]
Thanks for quick feedback!

Maybe a packaging issue then missing the default map.
