### ISSUE TITLE
Navigate branches in floating layout with keyboard

### ISSUE THREAD

**Issue by slmeyer** [insilmaril/vym#103]
I kind of expect to be able to navigate or traverse all branches and nodes in the map with the arrow keys up, down , left and right. This seem to work as long as VYM position all the new nodes. If I move a branch with the mouse, I need to navigate with the arrow keys as if it still is in the old position, that is for instance press down when the branch appears above current position (If moved from bottom to top). 
In the manual I read (3.2 Navigate ..) that "Within a set of branches, let’s call them a subtree, you can use [PgUp] and [PgDn] to go up and down" When I do that the current branch is moved up or down in the tree editor and the cursor does not move in the map.
After some editing it is no longer possible to reach all branches with the keyboard. This is for instance the case in the example map task.management. There I can only get to the topmost branches and nodes. It is not for me possible to navigate down through the list of months for instance.
This is for me an essential feature to be able to navigate and create new items without having to grab the mouse, in order to be able to be in the flow of my thinking. Otherwise I really love this software!

**Comment by insilmaril** [comment]
THanks for the comments. For the PageUp/Down: The manual is wrong here and this has gone unnoticed for many yeary. Finally someone read the manual :-)  For now I removed the entry in ddc3949ccce1c514d22527f09a8736be08d76550 

Selecting the branch of a subtree with "floating" layout is tricky, as there is no obvious left/right or higher/lower, the branches can be everywhere. in 2.9.26 usually only main branches attached to a center had this positioning, in 3.0 it will be a more common layout option. I'll try to implement something for 3.x, but this might take a while.

**Comment by insilmaril** [comment]
Implemented with cd44d98b8750bdf3fc193ea291104c8c957b0bbc
