### ISSUE TITLE
Package for Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by flyte** [insilmaril/vym#104]
The .deb download works fine on (K)Ubuntu 24.04 LTS, but it's not specifically listed on the [builds page](https://software.opensuse.org/download.html?project=home%3Ainsilmaril&package=vym). No rush, since everything seems to be working well, but I figured it'd need adding eventually.

Thanks for your work on this lovely bit of software :grin:

**Comment by insilmaril** [comment]
Thanks for the feedback, I added a build now for 24.04 LTS :-)
