### ISSUE TITLE
Allow free positioning of blocks

### ISSUE THREAD

**Issue by louxyy** [insilmaril/vym#127]
Hello everyone, 

when I create my mindmap, I sometimes want to place a block a little further away and not overlay on another block to highlight it, for example. 
If I try to move the block, it immediately comes back just above another block. 
I've found an alternative workaround by going to the block properties. I create a frame, with a white border to make it invisible, and increase the margin. 
In the Layout tab, I could see the "Free positioning of children" option. I tried it, but it didn't work. I'm not sure if it suits my needs. 

It'd be great if you could move a block by temporarily disabling automatic positioning. We could imagine free positioning by using the Ctrl + mouse combination.

Isn't that a good idea ? :)

**Comment by insilmaril** [comment]
Free position will be available in the 3.0 release, for a demo see
https://www.youtube.com/watch?v=21-tB3mDiks
