### ISSUE TITLE
Warnings: Default map and macros not found at startup

### ISSUE THREAD

**Issue by insilmaril** [insilmaril/vym#14]
In vym 2.8.1 on openSUSE Leap 15.3 the vymBaseDir is not set correctly, resulting in several warnings and unavailable demo maps and translations.

Workaround:

Start vym from shell or configure your Window Manager to do similar:

`cd /usr/share/vym; vym -l`

This forces vym to use /usr/share/vym as vymBaseDir

An updated package with fixed path is pending for vym 2.8.7, watch or even add the repository from:
[https://build.opensuse.org/package/show/home:insilmaril/vym](https://build.opensuse.org/package/show/home:insilmaril/vym)

**Comment by nfetisov** [comment]
The same with  2.8.7 on ALT Linux, cmake 3.19.7. 
Try to fix VYMBASEDIR via this patch: [vym-2.8.7-alt-vymbasedir.patch.txt](https://github.com/insilmaril/vym/files/6660705/vym-2.8.7-alt-vymbasedir.patch.txt)

**Comment by insilmaril** [comment]
Thanks for the patch! Fixed it slightly different, can you checkout HEAD in develop (2.8.8)?

Packages with this (and some other fixes) are now available here:
https://build.opensuse.org/package/show/home:insilmaril/vym

**Comment by nfetisov** [comment]
> Thanks for the patch! Fixed it slightly different, can you checkout HEAD in develop (2.8.8)?

Thanks, this works. Updated package for 2.8.8 is available in the ALT Linux Sisyphus repository.

**Comment by insilmaril** [comment]
Thanks for the feedback, closing now.

Unrelated: if you have an idea how to compile with DBUS using cmake, I'd be curious ;-)
