### ISSUE TITLE
Unable to write local language characters, they are triggering shortcuts 

### ISSUE THREAD

**Issue by insilmaril** [insilmaril/vym#2]
Reported by Vladimir Kuzmins in https://sourceforge.net/p/vym/bugs/125/

 Setup: I use Ubuntu 18.04 in English, but with "latvian(apostrophe)" keyboard layout/input source. Compiled VYM 2.7.1 with qt5 dev packages, downloaded from sourceforge.

Problem: It is impossible to type text in VYM nodes in Latvian with above setup. By trying to type "'a", "Alt+A" shortcut is triggered and node is inserted. Same for typing "'i", "'u"

Context1: With given keyboard layout typing "'a" ("[apostrophe]a") gives "ā" , which with "regular" "Latvian" layout would require "AltGr+a", which (may be) gets emulated and triggers behavior above.

Context2: Some shorts are possible to workaround openning Title text editor. Which works for 'e, 'a, but not for 'u, which seems to be global shortcut.

**Comment by insilmaril** [comment]
Related: https://sourceforge.net/p/vym/bugs/130/

**Comment by drossberg** [comment]
Is it possible to reproduce this with a German keyboard?
I tried to reproduce it with Debian buster and Qt 5.11.3, but there the left Alt key triggers the menu shortcuts and the right AltGr key triggers the special characters, as expected.

**Comment by insilmaril** [comment]
On several platforms indeed the Alt-... triggers the menu shortcuts. I occasionally see this myself :-(

Some platforms allow switching off the menu shortcuts shortcuts, I think once in KDE I managed to do so, but it's tricky at least.

Best would be to not use Alt for shortcuts at all, and leave these to OS.  

Long ago I started to consolidate the shortcut mess of all editors  in src/shortcuts.*  but this is still in an early phase - ideally there would be configurable and unified shortcuts.

**Comment by shemeshg** [comment]
I do like the shortcuts in Freeplane (Enter - for branch below, tab - for branch on the right),
They do make sense that do not require  switching keyboards to add branch (in my language it is different symptom but same issue)

**Comment by insilmaril** [comment]
I think best would be to rewrite the shortcut handling and allow configurable shortcuts. the "Switchboard" is a first step, but first the design needs to be thought through. There are special cases, e.g. in TreeEditor cursor keys have different meaning than in MapEditor.

Any volunteers?

**Comment by insilmaril** [comment]
Is this still regarded an issue? Otherwise I'd close the ticket for spring cleaning...

**Comment by shemeshg** [comment]
Can be closed

Thanks

**Comment by insilmaril** [comment]
Thanks!
