### ISSUE TITLE
Should VYM have option to scale Image, and set default size to it?

### ISSUE THREAD

**Issue by shemeshg** [insilmaril/vym#21]
When attaching external image, should VYM be able to modify it's size? and set default size for next time same image is inserted?

It is a question since, 
- it is very easy to modify image outsize VYM (Using GIMP on linux, or Preview on OSX)
- Freeplane don't have it either.

**Comment by insilmaril** [comment]
SIze can be modified using CTRL-[+|-]

Internally vym stores the original size (IIRC) and scales on load

A default size does not make sense I think: Sometimes I add little icons, sometimes huge screenshots - which size should be default?
