### ISSUE TITLE
Tree editor always appears

### ISSUE THREAD

**Issue by captavio** [insilmaril/vym#25]
Tree Editor appears with every file opened. Even when disabling, it appears again next time.

vym version: 2.8.8 - 2021-06-16
   Platform: openSUSE Leap 15.3
 localeName: de_DE.UTF-8
  tmpVymDir: /tmp/vym-QzNEgC
zipToolPath: /usr/bin/zip
 vymBaseDir: /usr/share/vym
currentPath: /home/01_volker_home
 appDirPath: /usr/bin
   Settings: /home/01_volker_home/.config/InSilmaril/vym.conf
 SSL status: supported
     SSL Qt: OpenSSL 1.1.1d  10 Sep 2019
    SSL lib: OpenSSL 1.1.1d  10 Sep 2019

**Comment by insilmaril** [comment]
State of tree editor is saved per map (which should be maybe changed one day), but does it work for specific maps for you? 

In the XML there is a settings entry with /treeeditor/visible key at the end of the file

**Comment by captavio** [comment]
Sorry, there is no such entry:

Sorry, inserting xml does not work

**Comment by insilmaril** [comment]
Just retested: TreeEditor does not open on first map, but at least the one in second tab

**Comment by insilmaril** [comment]
Fixed in ed279df3740e354a8382dc33788c2def510a8711 in version 2.8.36
