### ISSUE TITLE
File name in Tab is not displayed

### ISSUE THREAD

**Issue by captavio** [insilmaril/vym#26]
When opening the first new tab, after 'save as' the file name is displayed in the tab. For further tags, display keeps "unknown" until reloading the file.

vym version: 2.8.8 - 2021-06-16
   Platform: openSUSE Leap 15.3
 localeName: de_DE.UTF-8
  tmpVymDir: /tmp/vym-QzNEgC
zipToolPath: /usr/bin/zip
 vymBaseDir: /usr/share/vym
currentPath: /home/01_volker_home
 appDirPath: /usr/bin
   Settings: /home/01_volker_home/.config/InSilmaril/vym.conf
 SSL status: supported
     SSL Qt: OpenSSL 1.1.1d  10 Sep 2019
    SSL lib: OpenSSL 1.1.1d  10 Sep 2019

**Comment by captavio** [comment]
... further tabs ... "unnamed" ..      (sorry)

**Comment by insilmaril** [comment]
Huh. Nice catch, never noticed that :-P

**Comment by insilmaril** [comment]
Do you see this also for maps, which have been changed or only for unchanged maps?

I open a map s.vym, save as t.vym

Close vym and then load "vym s.vym t.vym"

Now saving t.vym as u.vym => tabname changes to u.vym    correctly

**Comment by captavio** [comment]
I figured out again. Obviously, it happened, when a file is created and saved without any editing. (Usually I save the file to have a filename and then start editing. See screenshot, see also status bar
![Screenshot_20211029_103000_Save_As](https://user-images.githubusercontent.com/93324001/139472616-1d65c6c4-806d-4c06-aabf-e492f0700f79.jpg)
.
