### ISSUE TITLE
Hide connection (?) , Verbindung verbergen

### ISSUE THREAD

**Issue by captavio** [insilmaril/vym#27]
In older versions it was possible to hide the connection between items. When oping older files, the connection is still hidden. It is also possible to edit this in the xml file, but no longer in the user Interface.

vym version: 2.8.8 - 2021-06-16
   Platform: openSUSE Leap 15.3
 localeName: de_DE.UTF-8
  tmpVymDir: /tmp/vym-QzNEgC
zipToolPath: /usr/bin/zip
 vymBaseDir: /usr/share/vym
currentPath: /home/01_volker_home
 appDirPath: /usr/bin
   Settings: /home/01_volker_home/.config/InSilmaril/vym.conf
 SSL status: supported
     SSL Qt: OpenSSL 1.1.1d  10 Sep 2019
    SSL lib: OpenSSL 1.1.1d  10 Sep 2019

**Comment by insilmaril** [comment]
Will be part of next builds (2.8.21+)

**Comment by captavio** [comment]
It works now in 2.8.27
