### ISSUE TITLE
Ubuntu 20 can't update VYM

### ISSUE THREAD

**Issue by nicolae788** [insilmaril/vym#32]
Hello.

In Ubuntu 20 apt installs version 2.6.11 Going to Help -> Check If Updates Are Available results in an warning : Please allow VYM to check for updates. 

Now, I have some maps created in 2.8 and opening those results in no text were there should be text.

Any suggestions ?

Thank you !

**Comment by insilmaril** [comment]
Seems Ubuntu maintainers are slow in picking up new releases, vym 2.6.11 is from 2017 :-(

For openSUSE and Fedora I create builds regulary here: https://build.opensuse.org/package/show/home:insilmaril/vym

Unfortunately debian based builds are not functional at the moment.

Also file format changed for vym 2.8, it is not backward compatible and also be careful not to overwrite your 2.8 maps with 2.6 - the could be data lost.

Details are in commit d2a3e0493fcfbd3b9ebb3b80bc5239fb0461c02c

**Comment by nicolae788** [comment]
Hello Uwe.

Thank you for your reply and claryfing this. I tried to build from source but ended when received an error from qmake that i miss script. After investigating a bit i realised that I have to install some 1.6 Gb of various non QT development libraries and decided not to. 

I first used vym on fedora 33 which after an update borked,  then tried on Rhel 8 which also borked  for a reason I do not remember and now I am on Ubuntu 20 which seems more stable. However i dual boot with Win10 so despite trying to make Linux a daily driver seems I have to move back and forth between OSes. The Windows VYM works perfect. 

Thank you for your support and for this excellent application.

**Comment by insilmaril** [comment]
Sorry to hear that. Unfortunatly I don't use Ubuntu, so I cannot help - that should really be done by Ubuntu maintainers. Debian also seem to be on 2.6.11:
https://packages.debian.org/search?keywords=vym

I'll ping the maintainer...

**Comment by nicolae788** [comment]
O.K. Thank you for your support. I'll wait for news !

**Comment by Jupek1** [comment]
Hi,

Today I did the following and compiled&installed the latest development version 2.8.24 - 2021-11-08 in Linux Mint 20.2 Cinnamon - works great!

Used Terminal + CMake GUI

xxx@mint202:~/Downloads$ **git clone https://github.com/insilmaril/vym.git**

Cmake GUI Configure -> errors
Synaptic: install several missing Qt5 dev tools
Configure & Generate OK!		Makefile etc. generated

xxx@mint202:~/Downloads/vym/build$ **make**	
...	
[ 98%] Building CXX object CMakeFiles/vym.dir/src/dbus/adaptorvym.cpp.o
[ 99%] Building CXX object CMakeFiles/vym.dir/vym_autogen/EWIEGA46WW/qrc_vym.cpp.o
[100%] Linking CXX executable vym
[100%] **Built target vym**

Uninstalled old version

xxx@mint202:~/Downloads/vym/build$ **sudo make install**
[sudo] password for xxx:                       
[  1%] Automatic MOC and UIC for target vym
[  1%] Built target vym_autogen
[100%] Built target vym
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/bin/vym
-- Installing: /usr/local/share/demos
...

Thanks Uwe for your excellent program! I've used it (Ubuntus old version, before update) several years.

**Comment by nicolae788** [comment]
Hello Uwe, Jupek.

Jupek, I did the same you described and indeed it worked. I had to install qt5-default and libqt5svg5-dev, qtscript5-dev, qttools5-dev. The Dbus error can be ignored as the dbus package was already installed and after installing one by one the above QT5 packages at some point it disappeared 

After installing the above packages "configure" from CMake-GUI worked o.k. and then "generate". 

Move into build directory, "make" and "sudo make install".

Works perfect. Thank you for the tip !

**Comment by insilmaril** [comment]
Hi guys, a couple of days ago I managed to get the Debian and Ubuntu builds running again, I'd be curious to get some feedback if the generated packages work for you:

https://build.opensuse.org/package/show/home:insilmaril/vym

**Comment by nicolae788** [comment]
Hi Uwe.

Package can be installed using CLI or package manager in GUI. However I do not get an icon to start it from the app launcher. If I install vym from the official Ubuntu repo, which it's 2.6.11, I get the icon. If I then update 2.6.11 with the deb file downloaded from the link above, the icon, again disappears. It's not a real issue this, as I can launch it from the CLI and detach it, but it would have been more convenient to have the icon :)...

I just saw your message about the new build for Ubuntu. I will try to see what's with the icon...these days.

Thank you for your efforts.
