### ISSUE TITLE
Images can not be inserted at the cursor position on the Note Editor

### ISSUE THREAD

**Issue by joejac** [insilmaril/vym#35]
Hello and thanks for VYM.
I try to insert an image at the cursor position, any place in the Note, but VYM always inserts it at the very beginning of the Note. Is not possible to insert images on the Note Editor?
Regards

**Comment by insilmaril** [comment]
Unfortunatly yes, the NE does not support images yet, also no bullet point lists and tables.

Though it shouldn't be too difficult from a technical point of view, I don't have the time for that in near future.

**Comment by insilmaril** [comment]
... but maybe mid-term ;-)  Stuff like lists and table would be quite useful, alrady works with copy&paste, but no edit controls.

**Comment by insilmaril** [comment]
Added in 80597384db2dfa01c52cd7539ff99c28cdec2eab

(No drag and drop yet)
