### ISSUE TITLE
Paste from copied or cut text goes allways to beginnig of string

### ISSUE THREAD

**Issue by ced-quarnbek** [insilmaril/vym#38]
from this version: Version 2.6.11 - 2017-11-14
Platform: Debian GNU/Linux 11 (bullseye)
localeName: en_GB.UTF-8
Path: /usr/share/vym/lang
vymBaseDir: /usr/share/vym
currentPath: /home/xxx/1/src/c/open_clean
appDirPath: /usr/bin

When editing the Note for a selected branch in the Node editor widget a copied or cut piece of text doesn't land where you put the cursor as you paste but lands at the beginning of the node.
if you paste in in the text or a with \n split line between two \n.
Whatever trick you use no way landa allways at beginning

**Comment by ced-quarnbek** [comment]
strange enough when doing cut and paste with edit menu the pasting happens where you want it

**Comment by insilmaril** [comment]
Thanks, this has been fixed 4 years ago, sadly debian maintainers stopped updating vym :-(

commit 08e825709fe45346ffc23e5bd4448fa7753b3b9c

**Comment by insilmaril** [comment]
I fixed my own debian builds, can you try it and provide feedback?

https://build.opensuse.org/package/show/home:insilmaril/vym
