### ISSUE TITLE
Increase/decrease font size of branch using CTRL-[+] and CTRL-[-]

### ISSUE THREAD

**Issue by insilmaril** [insilmaril/vym#4]
Copied from here: https://sourceforge.net/p/vym/feature-requests/71/

**Comment by thomasdn** [comment]
I second this. Any plans on implementing this?

**Comment by insilmaril** [comment]
I'll try to do this for 2.9 release, let's see

**Comment by insilmaril** [comment]
Added in version 2.9.518, bound for 3.0
