### ISSUE TITLE
Heading Editor and Line break

### ISSUE THREAD

**Issue by captavio** [insilmaril/vym#40]
1. Create a new item
2. enter a long text and close with return
3. text is displayed with a line break
4. open in Heading Editor
5. there is no line break
6. enter a line break before the one displayed in the map and close
7. item in the map now shows 2 line breaks
8. open item directly by double click and close with return
9. line break from item 6. is gone, item looks as in 3.

Expected: Step 6. should remove the automatically inserted line break
Step 8 should not do anything

**Comment by insilmaril** [comment]
Hm, the LB from 3 is not really a LB, but rather a word wrap, thus it's not visible in the HeadingEditor.

The manually added LB from 6 is a "real" one, but ignored in LineEditor which opens when double clicking (or just pressing return).

The solution would be to **always open the full HeadingEditor, if a real linebreak is there**. Similar to what's happening, when the heading is RichText already.
