### ISSUE TITLE
Rename also in menu?

### ISSUE THREAD

**Issue by tuxick** [insilmaril/vym#42]
It took me a while to find out how to rename an entry
*add to documentation?
*add to (rightclick) menu?

**Comment by insilmaril** [comment]
It's in the documentation, see chapter 3.3 - Modify and move branches in the documentation: Easiest way is to just press "Enter" key.

But I like the idea to enable F2, which is currently used for the "color subtree orange" macro. I am going to create a command "editHeading", which users can assign to F2 - if they want to.

**Comment by insilmaril** [comment]
New command available in 2.8.30 (not released yet, but the commit is here https://github.com/insilmaril/vym/commit/2300181e17ecdddd078798296627d50647604fda )
