### ISSUE TITLE
Does Not Comply with XDG Standard on mimeapps.list

### ISSUE THREAD

**Issue by N1X3L** [insilmaril/vym#43]
My new favorite mind mapper! Just one problem so far… installation never generates [MIME file type associations](https://wiki.archlinux.org/title/XDG_MIME_Applications). This file is not created:
```
~/.local/share/mime/packages/application-x-vym.xml
```
The expected behavior is that I could associate .vym files with `vym`. The actual behavior is that I must launch `vym`, and then open the file within the program.

```
Kernel: 5.17.1-zen1-1-zen | arch: x86_64  bits: 64 | compiler: gcc  v: 11.2.0 | Desktop: Budgie  v: 10.6.1 | Distro: EndeavourOS  base: Arch Linux
```

**Comment by insilmaril** [comment]
Happy to hear you like vym.

I don't know how you install, is this a package on arch? I'd blame the package maintainer, in my SUSE package it's there. You could compare the desktop files here:

https://build.opensuse.org/package/show/home:insilmaril/vym

**Comment by N1X3L** [comment]
[I have reported to the package maintainer.](https://bugs.archlinux.org/task/74550) Thank you!

**Comment by Scimmia22** [comment]
So every downstream packager needs to include it themselves? Why wouldn't you add it here if people should have it?

**Comment by insilmaril** [comment]
Hm it could be also tracked here in github and not just in OBS. The target destination then depends on platform, so cmake would probably need an update. 

Reopening for now.

**Comment by insilmaril** [comment]
Added the files in github to make packaging easier:
./config/vym.desktop
./config/vym.xml

Don't want to include it in the CMakeLists.txt for now, as the location really depends on platform and OS. Suggestions how to improve that are welcome

**Comment by insilmaril** [comment]
Both files are now installed with cmake install for UNIX-like platforms.
