### ISSUE TITLE
Spellcheck?  Default Borders?

### ISSUE THREAD

**Issue by Te-M** [insilmaril/vym#44]
Just started using this on Windows (very impressed so far) but I noticed there doesn't seem to be a spellcheck function.  Am I overlooking it?  Also, is there a way to make new entries default to having a certain border?  Thanks!

**Comment by insilmaril** [comment]
Hi, thanks for the FB and happy you like vym.

Unfortunatly spellcheck is not planned, at least not for near future by myself. If someone wants to add, I certainly can help.

Atm there is no default style, but what you could do is write a macro and use that, example:

Alt/S to open script editor, goto macros tab> and change one macro for a function key, e.g.

```
function macro_f1()
{
  map = vym.currentMap();
  map.addBranch();
  map.selectLatestAdded();
  map.setFrameType("RoundedRectangle");
  map.setFramePadding(5);
  map.setFramePenColor("#ff0000");
  map.setFrameBrushColor("#ffffff");
  vym.editHeading();
}

```
Hints: 
* For errors you can open the debug window with Alt-Shift-S
* On regular Windows/Linux installations you probably have to save the macros to a place where you as user can write. The path can be changed in settings dialog.
