### ISSUE TITLE
[feature request] Attachments (like notes)

### ISSUE THREAD

**Issue by Thomas131** [insilmaril/vym#45]
Hi!
Thanks VERY much for providing such a great software as FOSS!!! I am truely thankfull! I am currently migrating lots of my NextCloud-Deck Cards to Mindmap-Items (since I feel I have more overview over everything).

In NextCloud I can attach files to cards. It would be cool if (next to notes), you could attach files to a node.

Best Regards!
Thomas

**Comment by insilmaril** [comment]
Thanks for the nice feedback!

What you already now can do is add a "local" link to a file somewhere on your disk  Right click -> references -> Edit local URL
(no shortcut yet), or add one with "U" and set to file://C:/Users/... or wherever your file is

Including into the zipped map file is currently not planned - this would make the regular saving a bit slow I guess.

I am also using nextcloud and thought about syncing maps with tasks, but probably will settle for a trello sync sooner or later. Let's see, started an experimental branch on git a while ago ;-)
