### ISSUE TITLE
Couldn't start zip tool to compress data!

### ISSUE THREAD

**Issue by ghost** [insilmaril/vym#46]
Hey all,

I installed vym on gentoo using `emerge x11-misc/vym` and put the xcb use flag in /etc/portage/package.use as `x11-misc/vym xcb`.
I ran vym needing to use 'dbus-run-session vym` in the terminal (because I forgot to add the dbus flag lol)
When I tried to save a small mindmap I get the error stating
"Couldn't start zip tool to compress data!
The map could not be saved, please check if backup file is available or export as XML file!

ziptoolpath: 
args: -r /home/ryanl/Desktop/ImportantStuff/Research-Toyooka/ADNP/ADNP-mind-map.vym ."

I can export and open with xml so this isn't a big issue for me. It's important to note that while typing this I added the dbus use flag but still get the same issue (I haven't restarted my computer which maybe required here). Also important to note that this is version 2.7.500 development version. Perhaps I should look into making a ebuild of a stable version.

I just wanted to bring this up in case this still shouldn't be happening and I've stumbled on a bug. I've not made an ebuild before but would not mind making this my first ebuild so that gentoo can have a stable & updated version instead of 2.7.500 dev version. Let me know what you think and if you want me to try anything. Today I have to study so I'll check this tomorrow and just use xml exporting/opening to save my map. Sorry I didn't format this issue well but I need to get to studying lol.

**Comment by insilmaril** [comment]
Hi, can you please indeed try with 2.8.40 from develop branch?  (this is stable, using it every day on Windows and Linux)

**Comment by insilmaril** [comment]
Sorry, cannot reproduce without gentoo, looks like a packaging issue
