### ISSUE TITLE
can't save .vym file

### ISSUE THREAD

**Issue by peter149** [insilmaril/vym#48]
on Window 11 I use VYM Version 2.8.36 - 2022-04-29 (German language). I can't save my new map, got critical error. Button Speichern (CTRS+S) is grayed out.  Save as with new name is also impossible. What to do?

**Comment by insilmaril** [comment]
Hm, 

can you write into the directory? If a map (e.g. a demo map) is loaded as "readonly", the button will be disabled.

Any other error messages? Maybe also on console, if you start vym from within a terminal, e.g. with "vym -d"?

To save the map, you could also try exporting it as XML.

Last but not least you could update to 2.8.43
https://sourceforge.net/projects/vym/files/Development/

though I am not aware of a fix for saving recently.

**Comment by peter149** [comment]
I have installed the update 2.8.43.
It is possible to save a file 1x after creation and assign a name. Then "Save" is grayed out. It is also not possible to save under a different name, because no LOG file can be created.

**Comment by insilmaril** [comment]
I am trying to reproduce...

So you

1. Create a map and do some changes
2. You can "save" e.g. under test.vym
3. Apply another change
4. You try to "save as" and
"Save" is available (due to changes)? 
File cannot be saved critical error?

I just uploaded a version 2.8.45, where I changed the error message. Now in the last step you should get a "Map cannot be renamed". Could be an issue with lockfile handling on WIndows, which I have never seen on Linux

**Comment by insilmaril** [comment]
One more thing: Do you still see German, e.g. "Speichern"?  I also changed location of translations... (though somewhat incomplete in this version, that will need another update soon)

**Comment by peter149** [comment]
1. Installed 2.8.45
2. "Speichern" in same location
3. New error message, as you described

**Comment by insilmaril** [comment]
Thanks!

Reopening, need to investigate what happens with the lockfile.

**Comment by insilmaril** [comment]
I'm going to build a Windows binary today and upload it to SF again, can you provide feedback?

**Comment by insilmaril** [comment]
2.8.48 should be there in 20 min

**Comment by insilmaril** [comment]
Fix is included in 2.8.51, windows executable available on sourceforge, Linux packages on https://software.opensuse.org//download.html?project=home%3Ainsilmaril&package=vym
