### ISSUE TITLE
scripts/confluence.rb is a symlink

### ISSUE THREAD

**Issue by drossberg** [insilmaril/vym#5]
Something curious happened to scripts/confluence.rb: It's not a file but a symlink!
`git checkout` gives me `error: unable to create symlink scripts/confluence.rb: file name too long`

**Comment by insilmaril** [comment]
Hm, I need to fix this. Original file is in here:

https://github.com/insilmaril/confluence-ruby

**Comment by insilmaril** [comment]
Removed and readded the confluence script, should work now.
