### ISSUE TITLE
Ubuntu 20.04 unmet dependencies

### ISSUE THREAD

**Issue by efernbach** [insilmaril/vym#59]
downloaded .deb file tried to install using gdebi package installer. Error message: Error dependency is not satisfieable: libc6(>=2.34)

**Comment by insilmaril** [comment]
Thanks. I built it for Ubuntu 22 in OBS, I just added 20.04 and triggered a rebuild, can you try from here (once it's hopefully available):

https://build.opensuse.org/package/show/home:insilmaril/vym

**Comment by insilmaril** [comment]
hrm, which vym version are you refering to?

**Comment by efernbach** [comment]
I downloaded vym_2.9.0-beta-4-amd64.deb from https://sourceforge.net/projects/vym/files/Development/

**Comment by efernbach** [comment]
a minute ago I looked at https://build.opensuse.org/package/show/home:insilmaril/vym it looks like the Xubuntu 20.04 build failed

**Comment by insilmaril** [comment]
Just checked the build logs: The setup in 20.04 uses an older Qt version (5.12.8) and fails to compile QDate::startOfDay.

This has been introduced in 5.14.

You could patch this on your own or better update your Ubuntu, but for vym I'd rather stay on the Qt LTS version for some time before switching to Qt 6 later. Sorry, won't change the code here.

I am going to disable the build again for 20.04 :-/

**Comment by efernbach** [comment]
ok, thanks for your efforts. I guess I'll upgrade to 22.04
