### ISSUE TITLE
Add Keyboard Shortcut to Edit Font Size in Editor

### ISSUE THREAD

**Issue by jeffkeffer** [insilmaril/vym#60]
Someone previously asked about a similar feature, although this request pertains to richtext editing in the text editor pane, whereas previous request involved modifying text size for an entire branch from the main map editor.

My request is that a keyboard shortcut be added that allows the user to increase/decrease font size while editing richtext in the text editor pane. MSWord and LibreOffice both use Ctrl+[ ] to perform this function, which is my suggested keyboard shortcut, although MSWord also uses the alternative Ctrl+Shift+<>.

I'm using v2.9.0 beta4 for Windows, not sure if versions on other platforms include this feature or not.

P.S. The new dark mode is awesome!!

**Comment by insilmaril** [comment]
Thanks, nice idea! Though I guess I have to postpone to 3.x releases...

And thx for dark theme feedback :-)

**Comment by insilmaril** [comment]
implemented already   (development versions >= 2.9.520)  using Ctrl [+|-]
