### ISSUE TITLE
[Feature Request] Permanent Settings 

### ISSUE THREAD

**Issue by chromer030** [insilmaril/vym#86]
Currently for every map user needs to set a color, line thickness, background color etc.
And what if the user needs a same configuration for all maps? should he/she configure every map one by one?

Please add global settings, It's essential in this great app.

**Comment by insilmaril** [comment]
Thanks for the suggestion. The trick is to define and save your own default map, which will be used from then when creating new maps.

Map -> Save as default map

Or 

Settings -> Set path for new maps
