### ISSUE TITLE
Can I use ctrl and alt for macro?

### ISSUE THREAD

**Issue by kosirm** [insilmaril/vym#87]
Hi, I'm totally new to this program and community, yesterday I discovered this program and I'm totally stoned with possibilities.
Mr. Uwe Drechsel, you are a genius.

I have one question: You use from f1 to f12 and from shift+f1 to shift+f12 for macros.
For example: 
```
function macro_shift_f1(){
...
}

```
I wonder if I can use also other special keys (ctrl, alt)?
For example:
```
function macro_ctrl_shift_f1(){
...
}

```
or 
```
function macro_alt_shift_f1(){
...
}

```
I mean, that way I could expand my shortcuts tremendously...

Maybe also some other letters beside function keys?
For example letter d:
```
function macro_ctrl_shift_d(){
...
}

```
As far as I can see this is not possible, maybe I'm doing something wrong.
If not possible, please consider this as a feature request.

Thank you in advance for any reply!

**Comment by kosirm** [comment]
Please ignore all my suggestions and observations. I just realized that only one person works on the project, so I wonder how it is even possible that one person can write and maintain all this by himself. Unfortunately, I don't know C++ to help, so I'll be satisfied with what I get for free...

**Comment by insilmaril** [comment]
I like the idea, at least to add also CTRL to function keys.   ALT usually is already occupied by operating system shortcuts.

**Comment by insilmaril** [comment]
Will be part of the upcoming 2.9.26 release.
