### ISSUE TITLE
Small bug in ASCII export (Windows)

### ISSUE THREAD

**Issue by kosirm** [insilmaril/vym#88]
Hi, I encountered small bug in ASCII export, it is more a cosmetic thing, but anyway.
I use latest version of vym on Windows 11.
Steps to reproduce:
Run this file (it is very simple):
[ASCII Export Bug.zip](https://github.com/insilmaril/vym/files/12907404/ASCII.Export.Bug.zip)
This is file screenshot:

![Screenshot 2023-10-14 194439](https://github.com/insilmaril/vym/assets/54502/eb3c284d-7ceb-441a-bfad-aaeb5a7c7101)

This image is bug description:

![bug](https://github.com/insilmaril/vym/assets/54502/3be8ea32-1180-4192-a748-45dbe9b02b45)

This is possible desired result:

![desired_result](https://github.com/insilmaril/vym/assets/54502/59f9a3a6-7a09-44b6-8858-61d3bb229b0e)

**Comment by kosirm** [comment]
Please ignore all my suggestions and observations. I just realized that only one person works on the project, so I wonder how it is even possible that one person can write and maintain all this by himself. Unfortunately, I don't know C++ to help, so I'll be satisfied with what I get for free...

**Comment by insilmaril** [comment]
* Indention is also not correct for deeper branches
* 2nd and other MapCenters are missing line breaks

**Comment by insilmaril** [comment]
Above commit should fix it, but will see some more rework and testing.

**Comment by insilmaril** [comment]
Will be part of the upcoming 2.9.26 release.
