### ISSUE TITLE
Possibility to hide warning when saving XML

### ISSUE THREAD

**Issue by kosirm** [insilmaril/vym#89]
I'm using XML format because it is much more convenient for me, but every time I save a file (CTRL+S or Map -> Save) I get a warning with the possibility to save in compressed vym format:
 
![Save_XML_warning](https://github.com/insilmaril/vym/assets/54502/1e1fac65-bb0e-4e94-a16c-383cd09da95b)

Could you please add a checkbox "Remember my decision" or "Don't show again" so this warning will not be shown every time I save the file? I know that in that case it should be added to settings (to turn it on again), but please if it is possible, make this change.

I save files often, it's my habit to press ctrl+s after any edit but this warning also pops up every 60 seconds, which is my time for autosave, so it's pretty annoying.

**Comment by kosirm** [comment]
Please ignore all my suggestions and observations. I just realized that only one person works on the project, so I wonder how it is even possible that one person can write and maintain all this by himself. Unfortunately, I don't know C++ to help, so I'll be satisfied with what I get for free...

**Comment by insilmaril** [comment]
First: Thanks for all your feedback. And yes, vym is basically my pet project, but since nearly 20 years, so there is a chance I'll add/fix also user requests :-)

For this one here: Saving in xml would not save images, these go extra into the (zipped) .vym file, so this is not recommended. 

Why don't you want to save in .vym ?

**Comment by kosirm** [comment]
Thank you for your reply! Yes, I know, I'm working with text exclusively as I'm using mind mapping for writing, so I don't need images. I'm using XML firstly because I can add/delete/edit nodes(branches) outside of vym (for adding I just create uuid, which is trivial) and secondly because I can do versioning, merging etc. easily outside of vym. Imho XML open/save is such a huge advantage of vym, please don't take it away.

**Comment by kosirm** [comment]
Btw, you are right, I can make these 2 extra steps by myself (to zip extracted/edited XML file/folder back and rename .zip to .vym), which would be an easy workaround for my problem. So please consider this solved 👍 And as a bonus, as you rightly said, I can use also images, etc. You don't know how grateful I am for your hard work on this project!
