### ISSUE TITLE
QSocketNotifier: Can only be used with threads started with QThread

### ISSUE THREAD

**Issue by plutuplutu** [insilmaril/vym#92]
I'm getting this with build release and devel on up to date solus gnome and wayland:
`$ vym
QSocketNotifier: Can only be used with threads started with QThread
Trappe pour point d'arrêt et de trace (core dumped)
`
and only `core dump` with Xorg.
I found this post [https://forum.qt.io/topic/29587/solved-qsocketnotifier-can-only-be-used-with-threads-started-with-qthread/8](https://forum.qt.io/topic/29587/solved-qsocketnotifier-can-only-be-used-with-threads-started-with-qthread/8) but have no idea how to use it.

**Comment by insilmaril** [comment]
Hm, the core dump could be interesting, also building vym with debug flags, see also CMakeLists.txt:

```
# Switch on Debug mode with one of below:
# cmake -DCMAKE_BUILD_TYPE=Debug .
# set(CMAKE_BUILD_TYPE Debug)
```

But I somehow suspect this is related to the way Qt itself interacts with gnome and wayland. I have never seen this on 3 platforms  (Win, Mac, Linux) so far...  So if it crashes in Qt or xorg there is nothing I can do.

**Comment by plutuplutu** [comment]
If I uncomment `# cmake -DCMAKE_BUILD_TYPE=Debug .` I get 
`$ cmake .
CMake Error at CMakeLists.txt:27:
  Parse error.  Expected "(", got unquoted argument with text
  "-DCMAKE_BUILD_TYPE=Debug".
`

When I uncomment the other line I don't see any changes even running `vym -d`. There's just a couple attention messages about the use of deprecated things during `make`.

**Comment by insilmaril** [comment]
It's two different ways to generate the debug build: First is the command line when running cmake:

`cmake -DCMAKE_BUILD_TYPE=Debug .
`

The 2nd is to really remove comment and enable debug from within CMakeLists.txt

Either way maybe CMakeCache.txt may need to be removed, too.

**Comment by insilmaril** [comment]
Slightly modified documentation in 234d16bb921f08c24c8fb81c2f31f5e7fc7f90ff

**Comment by joebonrichie** [comment]
This was a packaging issue in Solus that made it's way to the stable repo. I believe this is resolved in our unstable repo now. Sorry for the noise!

**Comment by insilmaril** [comment]
Ah, thanks for the feedback!
