### ISSUE TITLE
Malware scanner complains about vym.exe

### ISSUE THREAD

**Issue by damoasda** [insilmaril/vym#93]
After I installed version 2.9.26 on my Windows PC, my Avast malware scanner blocked the file vym.exe because of a trojan horse. virustotal.com shows the same finding, see screenshot attached. I guess, it's a false positive alert but would be great if you find a workaround or let you files white-list by the corresponding scanners.

Download URL:
https://sourceforge.net/projects/vym/files/setup-vym-2.9.26.exe/download

![VirusTotal vym](https://github.com/insilmaril/vym/assets/46045854/10cd6c4e-a3c1-469c-ba3b-329db596ec49)

**Comment by insilmaril** [comment]
Thanks for the feedback, obviously I am concerned when there might be a risk here!

I also did the test on virustotal.com with same results and I agree this seems to be a false positive. My local scanners did not report an issue and I verified that the md5sum on sourceforge.net is identical to what I have created locally using innosetup and Qt creator.

Unfortunatly I would have a hard time to reach out to companies I even don't know and have contacts to get the to whitelist vym :-(   I hope they updated their databases soon, I would guess a lot of apps are created using the same tools.

**Comment by damoasda** [comment]
> Unfortunatly I would have a hard time to reach out to companies I even don't know and have contacts to get the to whitelist vym :-( I hope they updated their databases soon, I would guess a lot of apps are created using the same tools.

Hope is not necessary and would probably not help. Most companies offer a web page to scan and whitelist individual files, e.g.
* https://www.avast.com/false-positive-file-form.php
* https://www.avg.com/false-positive-file-form
