### ISSUE TITLE
Add "clear" button to 'Open Recent' menu

### ISSUE THREAD

**Issue by bmihelcic** [insilmaril/vym#95]
The project was moved from path shown in 2nd entry to a path of the 1st one, and being unable to remove the old path is a bit annoying. It just offers to create a new project after clicking on that non existent one.

VYM Version 2.9.26

![Screenshot_20240124_190320](https://github.com/insilmaril/vym/assets/25400528/449f427b-f07e-4c45-8b49-99778f9f3c28)

**Comment by insilmaril** [comment]
Right now there unfortunatly is no such option. 

As workaround you could edit the configuration file manually (best while vym is closed, otherwise it might be owerwritten again):

On Linux it's in $HOME/.config/InSilmaril/vym.conf  (On Windows using registry editor)

And there the entry "recentFileList"

**Comment by bmihelcic** [comment]
I was looking for such a file, thanks, it works!

**Comment by Bleyddyn** [comment]
I have changes for this issue, see https://github.com/Bleyddyn/vym/tree/clear_recent_95. However, I'm not sure what to do about localization. Do I need to add something to lang/vym.en.ts and/or the other translation files? If so, how?

**Comment by insilmaril** [comment]
Hm, I'd need a diff to see what you have changed. In general translation is handled by Qt itself: 

https://doc.qt.io/qt-6/qobject.html#tr

I use tr(..) everywhere and in the code only provide the English text.   Using Qt Linguist later on translators can create/edit the .ts language files, which will create .qm files when compiling. So if you only provide the English text, that's fine :-)

**Comment by Bleyddyn** [comment]
This should show diffs: https://github.com/Bleyddyn/vym/commit/da5258bd655bfe711805d506202b359a19f30858

**Comment by insilmaril** [comment]
This will show up in the next builds for 3.0, probably an alpha release in the next weeks.

Thanks for report and patch!

**Comment by insilmaril** [comment]
Above commit should refer to #94
