### ISSUE TITLE
Improve automatic positioning of branches

### ISSUE THREAD

**Issue by slmeyer** [insilmaril/vym#99]
Now when I add branch no 5 or 6 it is positioned on top of one of the others. It would be nice to have a mode where the branches are automatically re-organized keeping the layout neat. This would enhance the possibility of being in flow when brainstorming.

**Comment by insilmaril** [comment]
Usually branches are added as last sibling. With Shift/Ctrl-A  you could also add above/below current branch.

What do you mean with "neat layout"? Screenshots?

**Comment by slmeyer** [comment]
When I use just one word in the branches they are neatly arranged, like radiating from the center with approximate equal spacing. But when there is more text they are cramped together and in some instances on top of each other. Screenshot added
![Screenshot from 2024-04-05 23-43-15](https://github.com/insilmaril/vym/assets/3279963/7fa135d5-2674-4713-9918-1b5e166afc91)

**Comment by slmeyer** [comment]
That is when I just continue adding with A. Some of the same happens if I do some of them with Ctr A

**Comment by insilmaril** [comment]
Ah, the so called "main branches" attached to the center are first positioned around a circle. With more text, there will be overlaps as seen. For brainstorming I'd use only MapCenters together with autolayout switched on. Unfortunately in vym 2.9.x. all of this is a bit limited.

Main branches can be freely positions, so manually you can reorganize the layout.

In 3.x. there probably will be more layout options, stay tuned...
